### ISSUE TITLE
Steel Wind Strike

### ISSUE THREAD

**Issue by asimone** [Vauryx/AdvancedSpellEffects#11]
Steel Wind Strike is calling the wrong database call for sequencer. Current build is using `jb2a.sword.melee.01` but should now be `autoanimations.melee.sword.01.white.0` etc., etc.

**Comment by Vauryx** [comment]
Nope, the jb2a path is correct for the current jb2a patreon module. The autoanimations path is for, well, the auto-animations module.

**Comment by Vauryx** [comment]
Ahh yes sorry about that, there should have been a message letting you know to have it installed that wasn't appearing thanks to an oversight from me. Thanks for pointing that out!
