### ISSUE TITLE
[V10 beta] Error in VampiricTouch

### ISSUE THREAD

**Issue by Tupsi** [Vauryx/advancedspelleffects#122]
On casting an ASE enabled Vampirc Touch I get the following in console.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/3730499/213864984-f7c23427-f172-4baa-8cd8-c1cc30dde99e.png">

<img width="495" alt="image" src="https://user-images.githubusercontent.com/3730499/213865001-1a1800a0-1ef3-48ac-a785-ddfbf3c4ff0e.png">

**Comment by omega605** [comment]
Casting Eldritch Blast is not rolling damage with Midi auto-damage .
![UndefinedDamage](https://user-images.githubusercontent.com/71213476/213865768-c08ea180-547d-4be3-a53e-64154b2eed42.PNG)

**Comment by Tupsi** [comment]
ok, this is not a bug but a collision with A-A. Disabling the A-A animation in the config makes this go away. Vampiric Touch works as intended now, so closing this.
