### ISSUE TITLE
[V10 beta] Error in Call Lightning

### ISSUE THREAD

**Issue by Tupsi** [Vauryx/advancedspelleffects#123]
There is no damage roll to tokens in the 10 yard radius and the following error accurs in console.
<img width="507" alt="image" src="https://user-images.githubusercontent.com/3730499/213865454-3459a0dd-8ca8-4e5a-bcb9-ce78e1ec5f28.png">

<img width="624" alt="image" src="https://user-images.githubusercontent.com/3730499/213865491-13be1396-b0e2-4e54-a786-ebca4ae39136.png">

**Comment by Vauryx** [comment]
Could you try to hit the "Overwrite" button in the ASE settings for the spell and try again? That will set some default options on the spell itself to rule out some issues there. Thanks for the report!

**Comment by Tupsi** [comment]
I am pretty sure I hit that button for all spells I reported, just to make sure, but as requested did it again with the same result.

Here is another screenshot from the console for just the "press Call Lightning spell and place Template"-action I did.

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/3730499/214022890-d17c35b3-58d5-4be5-a354-8e2e65c01217.png">

**Comment by Tupsi** [comment]
I just clicked into one of the workflow items you see on the other screenshot to verify what is actually IN item.system.damage. Turns out nothing at all!:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/3730499/214023570-417443e4-baff-436e-a8c4-6f1927fe1f9d.png">

**Comment by Vauryx** [comment]
is there a damage formula on the initial Call lightning spell that is being cast?

**Comment by Tupsi** [comment]
no, there was none! I recreated the spell from the compendium and now everything works, so no bug, just my own stupidity, sorry for that!
I guess I got under the impression the "Overwrite" button would fix everything for me there is to fix. So I never got the idea of doing the spell from scratch.
