### ISSUE TITLE
[v10 beta] Detect Stuff "Add Tag" error: "tags.push is not a function"

### ISSUE THREAD

**Issue by Janner3D** [Vauryx/advancedspelleffects#125]
![image](https://user-images.githubusercontent.com/35965176/213865820-b94cd1b7-7a60-4355-a935-b22c4a5f078c.png)
 
While attempting to add custom tags for "Detect Stuff", I get this error, and the button to add or remove tags fails to function.

**Comment by Vauryx** [comment]
Make sure you have tagger installed and update the beta to 0.9.!9.90 and let me know if the issues are resolved
