### ISSUE TITLE
[V10 beta] Eldritch Blast

### ISSUE THREAD

**Issue by Tupsi** [Vauryx/advancedspelleffects#126]
Damage does not get rolled and damage states as "undefined" in the chatcard.

<img width="217" alt="image" src="https://user-images.githubusercontent.com/3730499/213866513-01f11b3e-480d-4da7-b349-b5c30495355b.png">

no visible error in the console though.

also the checkbox for Agonzing Blast is not saved. On reopening the configuration screen a checkbox is not checked again. Not sure if this is a bug or a feature though.
<img width="249" alt="image" src="https://user-images.githubusercontent.com/3730499/213866700-a5f51bab-13df-40e1-8b72-3bac9ed73569.png">

**Comment by Vauryx** [comment]
Could you export your MIDI settings and send them this way? Thanks!

**Comment by Tupsi** [comment]
uploaded you the settings on discord pm.

**Comment by Tupsi** [comment]
this works now with .93. Not sure if you changed something, but I recreated the spell from scratch and hit overwrite and now everything is fine!
