### ISSUE TITLE
[V10 beta] Detect Magic not detecting and throwing errors in console

### ISSUE THREAD

**Issue by Tupsi** [Vauryx/advancedspelleffects#130]
I set up Detect Magic with ASE and configured a tile with the following tag

`magical, evocation, red`

Now when I cast Detect Magic and move the actor token I get the following four errors with every step:

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/3730499/213875102-0b52c84a-f25b-4c33-bb8e-685ac128ab63.png">

also the "Detect Magic" is missing the outgoing animation which the "Detect Good and Evil" has as you can see in the next screenshot. The above actor does "Detect Good and Evil", the one south has "Detect Magic" active.
No matter, both throw the some error on the console.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/3730499/213875484-8387b1fe-8515-4da5-af48-2e13c0b4f4f3.png">

the "setup.js" lines are from ASE in the screenshots.

**Comment by Tupsi** [comment]
I just noticed that when you cast "Detect Magic" there is indeed a short animation of the wave, but it happens BENEATH the picture of the map. Only saw parts of it standing on the border of the map.

<img width="258" alt="image" src="https://user-images.githubusercontent.com/3730499/213877151-56930786-5fc9-4c54-be97-f8348a7965d9.png">

**Comment by Vauryx** [comment]
Remember to add the "ase-detect" tag at the start as per the wiki for "Detect Stuff". Please update the beta to 0.9.!9.90 as well and let me know if the other issues are resolved

**Comment by Tupsi** [comment]
works now with curent beta. Tested magic, good/evil and poision/disease. Do not forget to upgrade the wiki as only the text states "ase-detect" but the screenshots do not. Got me confused in the first place as well.
