### ISSUE TITLE
[v10 beta] Moonbeam-aoe size issue and no damage for tokens starting turn within area

### ISSUE THREAD

**Issue by MrPotatoZed** [Vauryx/advancedspelleffects#133]
Vauryx you are a gentleman and a scholar. Thanks for looking at all this stuff and taking the time to update to the v10. I know a lot of people, my table included, appreciate it. 

Just a few things I noticed in re Moonbeam. Only the first two have practical impacts on play:
1. The image size for the "bullseye" used to place the aoe is the correct 10ft diameter/5ft radius but when placed the aoe size becomes 5 ft diameter/2.5 ft radius. After placement I've seen it briefly flicker up to the correct size but it always goes back to 5ft diameter very quickly. No errors in console. 
2. It's dealing damage correctly for tokens entering the aoe but does not apply damage for tokens that begin their turn inside the aoe. Tested with combat active for tokens in the tracker. No errors in console. 
3. The spell added after initial casting is now called "activate moonbeam". My vote would be for the prior language of "move moonbeam" as more descriptive of what the action does but it's not a democracy and if your personal preference is the other way my table can easily live with it.
4. In the chat card showing damage being rolled/ applied the spell is shown as "activate moonbeam" and only the "command your moonbeam to move...." language is displayed instead of the full spell description that gives damage/save info. When initially cast the card shows "moonbeam" and contains the full spell info but thereafter it looks like everything shows up as activate moonbeam. Not a big issue at all; the damage scaling is being done correctly so far as I've seen. Just wanted to log the behavior in case it's not intentional. 

Tested on v10.291, 5e 2.1.2, in firefox and chrome on the forge. Only ASE+ dependencies + midi active. Spell setup/moonbeam tile info below. Spell info based on overwrite of SRD moonbeam:
![image](https://user-images.githubusercontent.com/85974617/213928659-d88e6921-847f-444e-b7ea-e3d8050c329f.png)

**Comment by Vauryx** [comment]
Please update to 0.9.!9.90 and let me know if the issues are resolved

**Comment by MrPotatoZed** [comment]
Looks resolved in the new beta; thank you!
