### ISSUE TITLE
Compendium is missing spells listed in github

### ISSUE THREAD

**Issue by Avitale34** [Vauryx/AdvancedSpellEffects#14]
Hello I am trying to find some of the spells on the github but they do not appear in the compendium it seems.

**Comment by Vauryx** [comment]
Hey - not all spells will be in the compendium as they are not SRD content and so I can't distribute them. You will have to create a spell for it, and then make it an ASE spell by checking the setting in its config page as shown on the WIKI.

**Comment by emirkmo** [comment]
Is it possible to add such spells to a new ASE compendium after it's been converted? And if so, can this be explained and listed in the Wiki on top of the warning about override?
