### ISSUE TITLE
Magic Missle - Cant select targets

### ISSUE THREAD

**Issue by Maradeurfv** [Vauryx/advancedspelleffects#150]
Hi, strange behaivior.
If I cast Magic Missle I get the prompt to select Targets for the darts. Butnothing happens, if I click with a leftclick on possible targets. I can not assign any darts.

**Comment by Tallon159** [comment]
Can you please tell me which version of foundry did you use and which version of ASE did you install ?

**Comment by Maradeurfv** [comment]
Foundry: 11 - 313
ASE: 0.9.5.6

**Comment by Maradeurfv** [comment]
Target mode doesn't work with any other spells either. The targets cannot be selected.

**Comment by Tallon159** [comment]
The module is not working with foundry 11. You can try this beta version in the meantime : https://github.com/Tallon159/advancedspelleffects/releases/download/11.0.0-beta0001/module.json
