### ISSUE TITLE
Steel Wind Strike doesn't work

### ISSUE THREAD

**Issue by HibaniPaws** [Vauryx/AdvancedSpellEffects#16]
Whenever I use steel wind strike (after setting it up with the ASE button) it doesn't show a dialouge or do anything.

**Comment by HibaniPaws** [comment]
> is just SWS causing an issue? Can you try it using the Find the Culprit module and only the required modules active to see if its a conflict issue with another module?

I used Find the Culprit! module and enabled only ASE with their required modules + Warp Gate and JB2A Premium, the problem still persists.

**Comment by Vauryx** [comment]
Can you press 'f12' when you use it and see if there are any errors in the console window?

**Comment by Vauryx** [comment]
fixed in 0.5.1.2
