### ISSUE TITLE
[Feature] Implement support Pathfinder 2e ?

### ISSUE THREAD

**Issue by Sasmira** [Vauryx/AdvancedSpellEffects#17]
Basically what the title says. PF2 is not supported by ASE.
Would be great to have that too !

thank's for your help
S.

**Comment by Vauryx** [comment]
Hello, Thanks for the suggestion! 
Unfortunately ASE is pretty 5e specific and wasn't really designed with other systems in mind at all. That combined with the fact that I have zero experience with PF or really any other system makes it really unlikely that ASE will ever get support for other systems from me. If however someone wanted to take a crack at adding support for other systems, I would be fully open to helping them with anything they might need.
