### ISSUE TITLE
Animation options for spells appear as numbers when converting

### ISSUE THREAD

**Issue by Tronikart** [Vauryx/AdvancedSpellEffects#18]
When clicking on ASE in, for example, Detect Magic, the "Select Wave Color:" and "Select Aura Color:" drop down menus appear as numbers, this wouldn't be much trouble but if it gets saved like this, when the spell is used it will error out, the error being that there are no

- jb2a.magic_signs.circle.02.divination.intro.0
- jb2a.detect_magic.circle.0

Which makes sense since the 0 should be a color, used Find the culprit with only the required modules to see if it went back to the intended behavior to no avail. 

I had this working a few days ago, I recently updated all my mods but don't recall which ones got updated, either way it wasn't that long since the last update.

Using:
- Advanced Spell Effects 0.4.0.1
- JB2A - Patreon Complete Collection 0.3.0
- Sequencer 1.1.3
- socketlib 1.0.9
- Tagger 1.1.5
- Warp Gate 1.9.1
- Foundry 0.8.9
- DnD5e - Fifth Edition System 1.5.3

With spiritual weapon the Weapon names will show on the initial window, then Spirit Type will be numbers, and due to that, it wont load the spirit Spirit Color options, the Spirit Attack Color will be numbers as well

**Comment by Vauryx** [comment]
fixed in 0.5.1
