### ISSUE TITLE
Moving any character on my map causes the following error

### ISSUE THREAD

**Issue by Eligarf** [Vauryx/AdvancedSpellEffects#20]
witchBolt.js:118 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'effects')
[Detected 3 packages: advancedspelleffects, lib-wrapper, drag-ruler]
    at witchBolt.js:118
    at Array.filter (<anonymous>)
    at _updateToken (witchBolt.js:116)
    at Function._call (eval at <anonymous> (libWrapper-errors.js:8), <anonymous>:4:14)
    at Function.callAll (foundry.js:153)
    at ClientDatabaseBackend.callback (foundry.js:8976)
    at foundry.js:8946
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateEmbeddedDocuments (foundry.js:8946)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:8835)
    at async Function.updateDocuments (document.mjs:366)
    at async DragRulerRuler.animateEntities (foundry_imports.js:90)
    at async DragRulerRuler.moveEntities (foundry_imports.js:41)

The spell is not currently running, but had been cast a couple times several days ago. I'm going to try stopping and restarting the server to see if this clears it up.

Active Modules:
----------
5e Encounter Builder v0.2.2;
About Time v1.0.4;
Ace library v1.3.0;
Active-Auras v0.3.08;
Active Token Lighting v0.2.17;
Advanced Macros v1.12;
Advanced Spell Effects v0.5.2.0.1;
Ambient Doors v2.2.5;
Arbron's Compendium Tools v0.4.3;
Arbron's Context Menu Library v0.2.1;
Autocomplete Inline Properties v2.5.0;
Autocomplete Whisper v0.3.3;
Automated Animations v0.6.56;
Automated Evocations - Companion Manager v1.4.6;
Automatic Journal Icon Numbers vv1.5.3;
Baileywiki Maps Premium v0.2.7;
Baileywiki Maps Towns v0.3.2;
Better Roofs v1.2.1;
Better Text Drawings v1.1.0.1;
Beyond20 companion module v1.3;
Calendar/Weather v3.1.10;
Changelogs v0.4;
Character Actions List dnd5e v4.2.3;
Chat Log Scaler v0.0.3;
Chat Portrait v0.5.20;
CodeMirror v5.58.3-fvtt3;
Collapsible Journal Sections v1.3.1;
Combat Enhancements v1.0.2;
Combat Utility Belt v1.6.2;
CommunityLighting by Blitz v0.4.7;
Compact DnDBeyond 5e Character Sheet v0.18.0;
Compendium Browser v0.7.1;
Compendium Folders v2.3.53;
Condition Automation v3.0.2;
Crash's Automatic Blind Rolls (5e) v0.8.2;
Crash's Tracking &amp; Training (5e) v0.6.7;
Custom Journal v1.2.1;
Custom Token Animations v0.2.51;
D&amp;D Beyond Importer v2.5.28;
Deprecated Modules v1.1.4;
DF Architect v3.0.6;
DF Chat Enhancements v3.3.0;
DF Curvy Walls v3.2.1;
DF Flags Editor v1.0.0;
DFreds Convenient Effects v1.14.1;
DFreds Droppables v1.3.1;
DFreds Pocket Change v3.1.5;
DF Settings Clarity v3.2.1;
Dice So Nice! v4.2.2;
Dice Tray v1.2.1;
DnD5e Helpers v3.0.3;
DNDBeyond Character Sheet for 5E v1.7.3;
DNDBeyond NPC Sheet v1.3.4;
DnDBeyond (Shared Compendiums) vv1.0;
dragon-heist (Shared Compendiums) vv1.0;
Drag Ruler v1.8.2;
Dramatic Rolls v1.5.0;
Dynamic Active Effects SRD v6.0.01;
Dynamic effects using Active Effects v0.8.62;
Easy Target v2.12;
Find the culprit v1.4.0;
Forien's Copy Environment v2.0.6;
Forien's Custom Fonts v0.1.3;
Forien's Quest Log v0.7.8;
Forien's Unidentified Items v0.3.17;
Foundry Community Macros v0.48.0;
FPS Meter v1.1.2;
FXMaster v1.2.1;
GM Secret Block v1.0.0;
Hidden Initiative v1.0.2;
Hide GM Rolls v0.11.0;
Illandril's Hotbar Uses v2.3.6;
Image Hover v1.1.8;
Initiative Double Click v1.2;
Input Expressions v1.3.4;
Item Containers v1.8.13;
Item Macro v1.5.5;
Jack Kerouac's Animated Spell Effects v0.6.8;
Jack Kerouac's Animated Spell Effects: Cartoon v0.1.9;
Jack Kerouac's Animated Tokens v0.2.2;
JB2A - Patreon Complete Collection v0.3.0;
Jinker's Animated Art Pack v0.6;
Journal Scaler v0.0.6;
Keybind Lib v0.3.4;
Laptop Form Fix v0.0.8;
Less Fog v0.8.6;
Let Me Roll That For You! v1.20;
Let's Trade 5e v0.3.0;
Levels v1.9.9.4;
lib - Color Settings v2.8.1;
Library: Chat Commands v1.3.3;
Library: DF Hotkeys v2.3.5;
libWrapper v1.10.8.0;
Lichtgeschwindigkeit (Lightspeed) v1.4.9;
Lock View v1.4.14;
Loot Sheet NPC 5e v3.2.3;
Macro Editor v1.0.9;
Macro Folders v1.2.23;
Magic Items v2.1.2;
Math.js v7.5.1-fvtt2;
Michael Ghelfi Audio Pack v1.2;
Midi QOL v0.8.79;
Midi SRD v0.1.03;
Minimal UI v1.0.10;
Mob Attack Tool v0.3.11;
Monk's Little Details v1.0.38;
Monk's Scene Navigation v1.0.18;
Monk's TokenBar v1.0.53;
Monk's Wall Enhancement v1.0.3;
Multiface Tiles v1.0.2;
Multilevel Tokens v1.5.2;
Next Up v0.1.12;
Parallaxia v0.3.6;
Party Overview v2.5.15;
PDFoundry v0.8.10;
Perfect Vision v2.10.6;
Permission Viewer v0.8.10;
Pin Cushion v1.5.0;
Pings v1.2.12+0.8.6;
Playlist Importer v1.7.0;
Polyglot v1.7.24;
PopOut! v2.4;
Popout Resizer v1.4.1;
Quick Encounters v0.8.6;
Quick Insert - Search Widget v2.5.0;
Sequencer v1.1.5;
Settings Extender v1.1.6+0.8.6;
Short Rest Recovery for 5E v0.4.3;
Simple Calendar vv1.3.75;
Simplefog - Manual Fog of War v0.1.18;
Smart Doors v1.2.9;
socketlib v1.0.9;
SortableJS v1.10.2-fvtt1;
Spells, Items, and Features Toolkit v0.4.3;
Split Journal v1.1;
Tagger v1.1.5;
Target Enhancements v0.9.5;
The Furnace v2.6.1;
The MAD Cartographer | Summer Bundle | Battlemap Pack v1.1;
Tidy5e Sheet v0.5.17;
Tidy UI - Game Settings v0.1.28;
times-up v0.8.22;
Token Action HUD v1.3.20;
Token Animation Tools v1.2.0.0;
Token Attacher v4.2.0;
Token Auras v1.14;
Token Health v0.4.4;
Tokenizer v3.4.12;
Token Magic FX v0.5.2.1;
Token Mold v2.13.1;
Token Stamp 2 for Foundry VTT - RollAdvantage.com v1.1.3;
Token Tooltip Alt v3.0.3;
Universal Battlemap Importer v2.2.0;
Vance's Sidebar Resizer v0.0.2;
Vehicles and Mechanisms v0.4.0;
Wall Height v3.6.0.0;
Warp Gate v1.9.1;
Weather Blocker v0.6.3;
Weather Control v4.0.3;
Your Tokens Visible v2.7.0;
Zoom/Pan Options v1.6.5;
zSync v0.0.4;

**Comment by Vauryx** [comment]
Aah I believe i've seen this pop up once before. Ana ctor for a token currently on the canvas may have been deleted which would cause this error. Could you make sure that every token on the canvas has an actor?

**Comment by Vauryx** [comment]
regardless - there will be a fix for this pushed shortly

**Comment by Eligarf** [comment]
Thanks, I deleted the tokens and replaced from actors, problem did not happen.
