### ISSUE TITLE
Dice Rolls

### ISSUE THREAD

**Issue by w1face** [Vauryx/AdvancedSpellEffects#21]
Can't actually see what the rolls are.  Just if they hit or miss.

**Comment by Vauryx** [comment]
I'm assuming you're talking about the 3 newest spells. The rolls themselves can be found in the console. There would be way too many to show them on the chat cards

**Comment by w1face** [comment]
Rolls like Magic Missile and Scorching Ray?

**Comment by Vauryx** [comment]
Yes. ScorchingRay for example makes 10 attacks at max level, more if any are with advantage/disadvantage

**Comment by w1face** [comment]
I can understand that... and whilst it looks great, if I have to open the console to see if someone has hit a creature within a margin that Shield would be viable or not... doesn't seem particularly user friendly.  Especially as if anything else is happening at the same time, the console is almost unreadable.

Unless I'm missing something, nowhere in the chat does it actually tell me what my attack roll is.

**Comment by w1face** [comment]
In addition, especially with Scorching Ray, many people would have Elemental Adept as a feat with fire as their chosen damage type.  How do they know if they've rolled a 1 on the damage?  Especially (as you've said) there are 10 different attacks at the same time with dice all over the screen.

Not to mention the narration aspect of the attacks.  If it just misses, or just hits, it's narrated differently.

As much as I love what you've done, I genuinely feel if the rolls are going to be hidden, it raises too many issues!

**Comment by Vauryx** [comment]
Those are fair points, I'm working on a better chat card solution for those spells I'll try to find a way to show the info cleanly

**Comment by w1face** [comment]
Excellent!  If I had even the slightest amount of programming or graphical skills, I would assist.  Thanks for all your hard work, and for listening. :)

**Comment by Vauryx** [comment]
Chat card update is out
