### ISSUE TITLE
[Suggestion] Adding support for MiDi-Qol reactions for ray spells

### ISSUE THREAD

**Issue by iAstinus** [Vauryx/AdvancedSpellEffects#27]
Currently, ray spells does not bring up reaction window (for a Shield spell, for a example) from MiDi-Qol. With roll results it is not that hard now to manually work around it, but it would be a great feature. Seem like low priority, though.

**Comment by bespezzano** [comment]
This would be a great addition.

**Comment by Vauryx** [comment]
I tried adding this - unfortunately with the way the ray spells work I can't really stop their execution once all the targets have been selected and the rays fired. This will most likely need to continue to be manually worked around , sorry!
