### ISSUE TITLE
Detect Magic Animation lingers

### ISSUE THREAD

**Issue by Avitale34** [Vauryx/AdvancedSpellEffects#3]
Detect Magic Animation lingers on token and can not get rid of without delete and dropping new token.

**Comment by Avitale34** [comment]
Getting this error too

AnimFunctions.js:1905 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'setFlag')
[Detected 2 packages: advancedspelleffects, socketlib]
    at Object.updateFlag (AnimFunctions.js:1905)
    at SocketlibSocket._executeLocal (socketlib.js:192)
    at SocketlibSocket.executeAsGM (socketlib.js:90)
    at Object.detectMagic (AnimFunctions.js:546)

**Comment by Vauryx** [comment]
All persisting animations can be removed by using the sequencer effect manager, there should be an icon for it on the left hand side menu. No need to delete and recreate the token.
Looking into the error that you're receiving -

**Comment by Avitale34** [comment]
It seems to happen when I cast it back to back, I was testing some tags and when I try to cast it a second time after removing the first it occurs.

**Comment by Vauryx** [comment]
I'm having trouble recreating your issue - can you try it using find the culprit and leave only the required modules installed (tagger, socketlib, sequencer, jb2a, ASE, advanced macros, midi-qol and DAE). If you could try this on a fresh world that'd be great too.

**Comment by Avitale34** [comment]
I am using token action hud to remove the concentration, would that have something to do with it?

**Comment by Avitale34** [comment]
Getting the same error with just ASE and it's dependents you have mentioned.

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'setFlag')
[Detected 2 packages: advancedspelleffects, socketlib]
    at Object.updateFlag (AnimFunctions.js:1905)
    at SocketlibSocket._executeLocal (socketlib.js:192)
    at SocketlibSocket.executeAsGM (socketlib.js:90)
    at Object.detectMagic (AnimFunctions.js:546)

**Comment by Avitale34** [comment]
I can invite you to the game if that will help!

**Comment by Vauryx** [comment]
That will actually help - please send me a message on discord - Vauryx#4507

**Comment by Vauryx** [comment]
Fixed in 0.0.8.3
