### ISSUE TITLE
compatibility with Character Actions List 5e-add spells to actions list

### ISSUE THREAD

**Issue by MrPotatoZed** [Vauryx/AdvancedSpellEffects#31]
Playing around with moonbeam and it's amazing. Can't wait for my party to resurrect the druid so I can show it off. I am running into a minor compatibility QOL issue though. The move moonbeam spell is auto-prepared so it shows up on a token actionHUD normally. However, with the Character Actions List dnd5e mod and the "group by action type" setting on token actionHUD prepared spells also need to be added to the action list to show up on the tokenhud. Any chance you could add a bit to toggle the "add to actions list" field for spells created by ASE effects? I understand this may be a bit niche and if my players learned to navigate their sheets it wouldn't be an issue but I thought I'd throw it out there. 

The layout of the token actionHUD with actions list and group by action type activated and the button to toggle the add to actions list field are shown below. At least in my experience, the action/bonus action/reaction/special action categories added by the actions list mod help players remember what actions they have left and seem to be a bit easier to follow as compared to the normal magic items/ inventory/spells/features breakdown. 
![image](https://user-images.githubusercontent.com/85974617/142692286-0b282c2c-45dd-4b41-a6b8-c46a95c6b4c9.png)

**Comment by Vauryx** [comment]
Hey - I understand what this would require - though the amount of work involved may a bit more than worth the effort as I would need a toggle in all of the spells that add at-will spells for it to be auto-added to the list if that specific module is installed. This also opens the floodgates into adding module specific options which could very quickly get out of hand. This will have to keep being managed by you manually I'm afraid, sorry!

**Comment by MrPotatoZed** [comment]
Thanks for taking a look at it and that makes sense. I would note that it's a pretty popular mod (12.8% install rate on the forge at least) but I know you've got a lot on your plate and have to pick your priorities. Thanks again for all the hard work you've put into this. Just amazing how it's grown in such a short period of time.
