### ISSUE TITLE
[Suggestion] Use crit damage option selected in settings + MidiQoL

### ISSUE THREAD

**Issue by Arcainne** [Vauryx/AdvancedSpellEffects#32]
Currently, it seems like this module uses the 5e default critical rules for damage, i.e., double the damage dice. There are other options available for how to handle crit damage in the base 5e system settings (along with other options in MidiQoL). I'm currently using the "Critical Damage Maximize Dice" option (max base damage + roll crit damage dice), so the crit damage for Scorching Ray in the example image below should be 12 + 2d6, for a minimum damage of 14 (if I roll two 1's for crit damage). It would be nice if this module piggybacked off of the selected crit damage setting. Otherwise, awesome mod!!

![ase-crit-screenshot](https://user-images.githubusercontent.com/4230871/142746781-42c55aa8-974c-4f67-a20e-5e76ab05e897.jpg)

**Comment by Vauryx** [comment]
This should be included in the next update
