### ISSUE TITLE
[Suggestion] Way to edit the dice entry

### ISSUE THREAD

**Issue by dsakura** [Vauryx/AdvancedSpellEffects#33]
Hello, firtst many thanks and congratulations for your great work! A way to edit the dice entry will be nice. For example, on my table I use the min2 to count 2 when the result is 1 due to Elemental Adept feat. If it is possible to edit from json, it would be nice to have a guide maybe.
Thank you!
edit. its easy to edit json lol Good to write some note about it.
edit2. Okay, what I think is missing is an entry to add / edit the dice rolled in the critical, when it is critical it is not rolled with the min2. Thx again

**Comment by Vauryx** [comment]
Hey - I think what you're asking for are custom crit rules? Unfortunately that'd be a little too involved to add at the moment. I'll be adding in support for Scorching Ray and Eldritch Blast to use the alternate 5e crit rules in the system settings - but that is probably going to be it for custom crit rules
