### ISSUE TITLE
Spiritual Weapon uses wrong attack stats

### ISSUE THREAD

**Issue by Tupsi** [Vauryx/AdvancedSpellEffects#35]
when I have configured to use ASE for Spiritual Weapon like you say in your wiki the Attack Roll Bonus of the weapon when cast is modified to 

"- @mod - @prof + 10"

which nullifies fine any mod/prof bonus on the weapon actor but adds a flat+10 in the end. The actor I cast that with currently only gets to a +5+3=8, so I was wondering where that +10 comes from and if you could change that logic to pull the correct stats from the actor the moment it is cast and put that for the +10 instead.

**Comment by Tupsi** [comment]
my bad, I overlooked a magic item giving +2. sorry for this.

**Comment by Tupsi** [comment]
after rechecking stats and you telling me on discord how you calculate that I would advice to use the mod, prof und msak values instead. Otherwise people with any spell attack bonus will not make it to the SW.

**Comment by Vauryx** [comment]
Addressed in next update - Spiritual Weapon now properly takes into account any melee spell attack or damage bonuses and isn't using spellDC to calculate the attack bonus anymore, instead using the caster prof + mod
