### ISSUE TITLE
suggestion: expand flexibility for magic missile spell

### ISSUE THREAD

**Issue by SR5060** [Vauryx/AdvancedSpellEffects#37]
would be great to use a less strict spell title to "unlock" the magic missle spell features so that if could be used for other spells. maybe something like search for any spell with "MM" or something like that?

**Comment by Vauryx** [comment]
Spells are no longer tied to the spell name as of 0.8 - if you update now you should be able to add it to any spel

**Comment by SR5060** [comment]
Yes sorry, bad timing. I read the release note just after submitting this
