### ISSUE TITLE
Magic Missile

### ISSUE THREAD

**Issue by bespezzano** [Vauryx/AdvancedSpellEffects#38]
Hi,

Just noticed that damage in Magic Missile is not being counted correctly when more than 1 dart goes to the same creature. Not sure if it's related to midi-QOL, but the HP is being calculated using the same base HP for each dart. In this example the 3 darts are going to the Sea Horse but only the last one is automatically counted as damage :

![image](https://user-images.githubusercontent.com/24845837/143380016-990981b0-442a-48f5-b978-b9b0f363bad3.png)

Edit: I've tried it again as GM and it works fine, it only seems to be incorrect when cast MM as a player.

Damage Card as GM working correctly:
![image](https://user-images.githubusercontent.com/24845837/143381476-4e56a2c1-7e68-4600-91b7-2d7232e83cec.png)

**Comment by Vauryx** [comment]
Weird - it seems to be working correctly as a player or as a GM for me. Could you see if there are any console errors on either the GM or the player client when the damage isn't applied correctly? Also, is the issue just visual with the damage cards (those aren't being generated by ASE) or is the actual hp on the actor also incorrect?

**Comment by bespezzano** [comment]
No error messages in the console on either side. The issue is not just visual, the actual damage in the token follows what's shown in the damage cards, so when I cast the spell as DM, the cards and total hp in the target are correct. When a player casts it, the damange cards are not calculated correctly as per my screenshot above (basically the damage calculation for each dart is taking the initial hp rather than the updated hp). Thanks for your time.

**Comment by bespezzano** [comment]
Did some more testing and managed to get some issues as DM as well.

As DM:
-When the 3 darts have different damage, all works correctly.
-When the 3 darts have repeated damage, the hp used to calculate is not taken correctly:

Here's an example, 
Dart 1 = 5, 
Dart 2 = 3
Dart 3 = 3

HP calculation for the 2nd dart should use 279 but uses 284 (hp before anything hit instead)

![image](https://user-images.githubusercontent.com/24845837/143518800-7874b6c6-aa3e-48d6-962b-2fe18d870f67.png)

**Comment by Vauryx** [comment]
Could you try this with only the required modules (plus MIDI) installed? Just want to confirm its not a module conflict issue

**Comment by bespezzano** [comment]
Unfortunately, same results.

Active modules:
![image](https://user-images.githubusercontent.com/24845837/143522240-618b5b0e-b1a3-495a-8936-a6fe6b3c247d.png)

**Comment by Vauryx** [comment]
Weird - could you export your midi settings and send them my way? Maybe I could reproduce the issue with your settings

**Comment by bespezzano** [comment]
Sure thing, here you go. Anything in particular I should be tweaking in the midi settings?

[fvtt-midi-qol-settings.json.txt](https://github.com/Vauryx/AdvancedSpellEffects/files/7606289/fvtt-midi-qol-settings.json.txt)

**Comment by bespezzano** [comment]
Hiya, did you manage to replicate the issue? Cheers, Bruno

**Comment by Vauryx** [comment]
Heya - sorry about the late reply. Lots of real life things meant I hadn't had a chance to properly develop ASE for the last two weeks. I wasn't able to replicate the issue with your MIDI settings but I also haven't yet explored everything I could. Will update this ticket soon with what I find (hopefully early next week)

**Comment by Vauryx** [comment]
Could you update now and see if you're still getting the same issue?

**Comment by bespezzano** [comment]
> Heya - sorry about the late reply. Lots of real life things meant I hadn't had a chance to properly develop ASE for the last two weeks. I wasn't able to replicate the issue with your MIDI settings but I also haven't yet explored everything I could. Will update this ticket soon with what I find (hopefully early next week)

Hey, thanks for the update and no need to apologise. I will try and test it as soon as my player is available and let you know.

**Comment by bespezzano** [comment]
Hi, unfortunately still the same issue. It actually got worse, now after selecting targets for the firs 3 darts, he's getting a new window to select 2 more darts and seems on a loop as it keeps popping up after casting.

**Comment by Vauryx** [comment]
Seems like something may be wrong with the item or actor itself. Can you try it with a different actor and convert a new magic missile from the srd compendium as well just so we can be sure

**Comment by bespezzano** [comment]
I'll try a new actor tomorrow, I did try with a newly imported spell in my
last test.

**Comment by bespezzano** [comment]
My player is not available today but I tried it as GM using a new actor and importing a the srd spell. From my tests using the 3 darts:

1. 3 different targets, one dart each, it all seems to work.
2. 2 targets, 1 + 2 darts (second target) all good (even with same damage on the 2 darts on the 2nd target)
3. 1 target, all 3 darts:
     a. different damage on 3 darts, all good
     b. same damage on 2 darts and 1 different, all good
     c. same damage on the 3 darts, only 2 seem to be counted (see pic below)


![image](https://user-images.githubusercontent.com/24845837/145125450-da0048ef-3dbd-4e3a-b76a-7ccfdc697370.png)

**Comment by Vauryx** [comment]
that's...very strange. So the issue is if all 3 darts are on the same target and all 3 have the same damage? I'll try to replicate on my end - thanks for the work testing! 
So it looks like it occurring in all the cases earlier was probably due to something weird with that actor I guess

**Comment by Vauryx** [comment]
Is this still occurring with 0.9?
