### ISSUE TITLE
[Suggestion] Give a bit more flexibility allowing for changes like radius

### ISSUE THREAD

**Issue by FGiorgi** [Vauryx/AdvancedSpellEffects#39]
This module is amazing! Let´s start with that^^
But I think it could be even better if it was possible to tweak the various details of the spells a bit more (especially now that they´re not tied to the name anymore).
Let´s take Fog Cloud for example: the only thing that´s tweakable is the number of walls. It would be neat to be able to tweak the radius of the cloud (so the same effect could be used for other stuff like smoke mephit death burst or homebrew "cloud creating" spells), same would be amazing for Darkness. 
I don´t really know how everything works under the hood but if it was possible to have the ability to tweak the spells settings it would be amazing :)

**Comment by Vauryx** [comment]
Its radius should currently be tied to the level that its cast at, but you're right now that its not tied to the name it should have a separate radius setting. Added to list

**Comment by Vauryx** [comment]
This will be included in the next update
