### ISSUE TITLE
Generated error due to file path with Call Lightning Ground effect

### ISSUE THREAD

**Issue by kylania** [Vauryx/AdvancedSpellEffects#4]
The ground crack effect for Call Lightning in  version 0.0.8.3 has the URL incorrect resulting in an error on screen and in the console.log.  The cause seems to be the anim reference has the file path backwards as seen here:

Line 296 of AnimFunctions.js

let groundCrackAnim = `jb2a.impact.ground_crack.blue.0${groundCrackVersion}`;

should be:

let groundCrackAnim = `jb2a.impact.ground_crack.0${groundCrackVersion}.blue`;

There's a few other locations in the same file where the references are in the correct order.  Backtics keep messing up the formatting, but the blue comes after the 02 basically. :)

**Comment by Vauryx** [comment]
Sorry about my laziness with updating the read me - I'm in the process of a restructure for this module and have fallen a bit behind on that front. Those paths will exist in the DB after this coming update tot he JB2A module. (Most likely today)
