### ISSUE TITLE
Mirror Image not working

### ISSUE THREAD

**Issue by gravagehulk** [Vauryx/AdvancedSpellEffects#43]
I installed the module and all dependencies. I do not have the Patreon JB2A (which as far as I know, is just cosmetic). When I cast the converted Mirror Image spell, it creates an effect from Dfreds instead and generates an error about JB2A library.

So, is Dfred's convenient effects conflicting, or is it because I don't have JB2A patreon? Because all I really want is the automation of attacking the images. I don't care about the effects.

**Comment by Vauryx** [comment]
Heya - Sorry, Yeah the patreon version of JB2A is required for ASE. ASE is a pretty large time drain and keeping up with a separate free and patreon version would be very difficult. It is something I want to do eventually, but hard to see it happening in the very near future at least.

**Comment by gravagehulk** [comment]
Okay, but that's why it's failing? I wouldn't have thought that the visual was a dependency for the automation to work.

**Comment by Vauryx** [comment]
The animations and the automation all happen together - so if part of the animation fails during it then that halts the flow of the code - Could you send a screenshot of the console (f12) when the error appears?

**Comment by gravagehulk** [comment]
![image](https://user-images.githubusercontent.com/69117052/144673883-4b86562d-0677-47ac-9d66-291efb77948b.png)

**Comment by Vauryx** [comment]
Could you include more the console please?

**Comment by gravagehulk** [comment]
![image](https://user-images.githubusercontent.com/69117052/144676230-c9c39243-b659-4bb8-b72e-508a65cfe873.png)

**Comment by Vauryx** [comment]
ohh I see what's happening - yeah concentration needs to be handled by MIDI for it to work

**Comment by gravagehulk** [comment]
It is.

![image](https://user-images.githubusercontent.com/69117052/144676511-1a306449-fa58-4b2a-a9c9-32bb4cb80b49.png)

**Comment by Vauryx** [comment]
Would you be able to send a screenshot of the concentration effect on your actor from Mirror Image? I'm not sure how Dfred's effects adds it and if it changes anything regarding the effect. You should probably try this with only the required modules installed to see if it would work without the patreon version

**Comment by gravagehulk** [comment]
What exactly would you need a screenshot of? The effect details on the "Effects" tab? Or the icon? Defreds just applies the "concentration" condition. Midi handles the automation with respect to removal. To be honest, I'd never sacrifice Dfreds for this one effect/module anyway. I use Defreds to handle all of my effects in the game and Midi is designed to work with it.

**Comment by Vauryx** [comment]
Ah yes - I'll try to add compatibility with Dfreds effects after the next round of changes

**Comment by gravagehulk** [comment]
Thanks. If there's anything I can do to help/test, I will. I'd like to be able to use this as it's a cool feature.

**Comment by gravagehulk** [comment]
Just an update:

I caved and bought the patreon version of JB2A. Mirror Image still doesn't work. In fact, it doesn't look like any of the actual settings show up in the spell after it's converted (see below). I do see these settings after converting Eldritch Blast (under the gear). When doing an attack, it just hits/misses as normal using Midi-QoL.

![image](https://user-images.githubusercontent.com/69117052/144754841-9450849b-5f56-4a51-94df-5bc9aef41336.png)

**Comment by gravagehulk** [comment]
Update: IT IS WORKING! Even with Dfred's on. I had damage on Midi set to manual (not fast forward) and I didn't realize it was waiting for the damage roll to resolve everything. The only issue I have now is the duplicate mirror image effects from Dfreds, but I will figure that out. Cool module. Thanks for all of your help.

**Comment by Vauryx** [comment]
oh awesome! Glad its working, sometimes if the correct settings for the spells aren't showing up, temporarily switching to a different spell effect and switching back can resolve it. 
There's a duplciate mirror effect? Are both MIDI and Dfreds adding concentration?

**Comment by gravagehulk** [comment]
Yes sir. Dfreds adds an effect from Tokenmagic, so there are three images (in a tighter circle) within the ones created by your module. You can kind of see it in my screenshot. Pretty trippy. I can just remove the Dfreds effect to fix this. I don't see any way to change Dfreds so that it doesn't apply the visual effect for this one spell, but it's fine. I really just wanted the automation, so I'm glad it's working.

**Comment by Vauryx** [comment]
ahh I thought you meant a second concentration active effect on the character. Glad its working!
