### ISSUE TITLE
general error in combat even without use of ASA

### ISSUE THREAD

**Issue by Tupsi** [Vauryx/AdvancedSpellEffects#48]
latest ASA throws this every attack, even though no ASA spell is involved. 

![image](https://user-images.githubusercontent.com/3730499/146142488-18ab99a5-4976-434e-92bf-4db25ffe1eef.png)

my array has `name: false` in.

**Comment by Tupsi** [comment]
talked to wasp, he will change the name field to default to null, so 
Sequencer.EffectManager.getEffects().filter(effect => effect.data?.name.startsWith(`MirrorImage-${target.id}`));
should work afterwards.

**Comment by Vauryx** [comment]
Fixed in 0.8.5.5
