### ISSUE TITLE
Tasha's Summon Aberration Bug

### ISSUE THREAD

**Issue by webmaster94** [Vauryx/AdvancedSpellEffects#50]
First of all, I would like to thank you for this wonderful module. It really makes the more complex spells that foundry's DND 5e system doesn't support well work much better. I think they should really work with you to see if some of this functionality can be implimented into the system itself.

But to my issue. I have encountered a small bug where the HP does not appear to be updated for Summon Aberration. I tried it for all three types of summons and the spell does not update their HP when cast at 5th level, it uses the HP of the base token. All other scaling effects appear to be being applied correctly. 

Foundry Version: 0.8.9
DnD 5e Version: 1.5.3
ASE Version: 0.8.5.2

Any assistance on this would be greatly appreciated.

**Comment by Vauryx** [comment]
Thanks for pointing it out. I'm in the middile of a big overhaul at the moment, but should get this fixed soon!

**Comment by Vauryx** [comment]
could you try this with the new update and see if it persists

**Comment by webmaster94** [comment]
Absolutely, will check now.

**Comment by webmaster94** [comment]
Issue appears to persist. I used find the culprit (https://github.com/Moerill/fvtt-find-the-culprit) to ensure no module conflicts. Here is the screen explaining the 9 other modules active: 
![image](https://user-images.githubusercontent.com/85364225/150579105-ee5251d0-3791-4087-a527-a3fa94cb258c.png)


Diagnostic Information:
Foundry Virtual Tabletop: Version 9, 9.242
Game System: dnd5e, 1.5.7
Active Modules: 10
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 OPR/82.0.4227.50
GPU: ANGLE (NVIDIA, NVIDIA GeForce RTX 3090 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9613)
Max Texture Size: 16384

Scene: 8400 x 8400 | Grid Size: 140 | Padding Percentage: 0.25
Walls: 107 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 16

Actors: 345 | Items: 466 | Journal: 783 | Rollable Tables: 41 |
Playlists: 57 | Compendium Packs: 29 | Chat Messages: 14399

**Comment by webmaster94** [comment]
I will mention that Summon Beast also appears to not scale at all.

**Comment by Vauryx** [comment]
Thanks for the info! I'll look into it for the upcoming update

**Comment by Vauryx** [comment]
For the Tasha's scaling to apply correctly - the spell names do have to be exact. Are your spellsnamed "Summon Aberrant Spirit" and "Summon Beast" respectively?

**Comment by webmaster94** [comment]
You have the spell name incorrect. The spell name is "Summon Aberration", see Tasha's Cauldron of Everything pg. 109. I do have Summon Beasts correct.

**Comment by webmaster94** [comment]
The odd thing is that didn't seem to be the issue. I modified summonCreature.js line 213 so it reads as follows:
`case game.i18n.localize("ASE.SummonAberration"):`

However, that didn't seem to fix the issue.

**Comment by Vauryx** [comment]
ahh that's my mistake - I'll have that fixed 
haha good thought - butt he line you would need to change to fix it on your end would be 
`languages\en.json line 25`
` "ASE.SummonAberrantSpirit": "Summon Aberrant Spirit",` 
to
` "ASE.SummonAberrantSpirit": "Summon Aberration",`

**Comment by webmaster94** [comment]
Never mind, I am an idiot. For some reason I managed to not check "Use Tasha's Scaling". I thought for sure that was checked.

**Comment by webmaster94** [comment]
Also I can confirm that the Aberration is working as expected once I changed the line in the en.json file as you recommended in your reply.

**Comment by Vauryx** [comment]
Change made - will be fixed with the next update

**Comment by Vauryx** [comment]
Fixed with v0.9.1
