### ISSUE TITLE
Other 'Detect' Spells?

### ISSUE THREAD

**Issue by nmason0711** [Vauryx/AdvancedSpellEffects#51]
Leaving this note here like Vauryx asked: 

Is there a thought or plan to make Detect Evil & Good / Detect Poison & Disease  in a similar fashion to Detect Magic? 

Or is there a way to set up Detect Magic on those spells in a different way?

**Comment by Berytak** [comment]
A detect traps would me neat, too.

**Comment by Vauryx** [comment]
added with 0.9.3
