### ISSUE TITLE
Version 9 Foundry Mirror Image - Attacks no longer resolves against images

### ISSUE THREAD

**Issue by gravagehulk** [Vauryx/AdvancedSpellEffects#53]
I know the module hasn't been updated for Version 9 yet, I just wanted to test and provide feedback.

The first thing I noticed was that the Mirror Image effect doesn't seem to be working right. It creates the duplicate images, but it no longer resolves the attack/damage against the the mirror image. It just applies damage directly to the target. I do have Midi QoL enabled and I compared the settings to my 0.8.9 environment. They are identical (everything was just copied over). I also grabbed a new copy of mirror image from the compendium and converted it to ASE again with the same result. Here's a screenshot:

<img width="294" alt="Screen Shot 2021-12-27 at 1 47 55 PM" src="https://user-images.githubusercontent.com/69117052/147502875-2e82d19c-6cf1-4799-806b-ef5c09d0f979.png">
<img width="542" alt="Screen Shot 2021-12-27 at 1 51 42 PM" src="https://user-images.githubusercontent.com/69117052/147503039-acbab7c8-da57-4f43-aed3-faa49fc03b42.png">

**Comment by Vauryx** [comment]
hmm - thanks for pointing it out. There will be an update this week that should resolve a bunch of these issues

**Comment by gravagehulk** [comment]
Update: As of 0.8.5.5 this issue is still occurring.

**Comment by Vauryx** [comment]
I think this is actually due to a change in MIDI-QOL and not the V9 update. The next update should fix it regardless

**Comment by gravagehulk** [comment]
I don't think so. Running 0.8.9 Foundry on my other system with Midi QoL 0.8.100 and ASE 0.8.5.5, it appears to be working fine:

![mirror image](https://user-images.githubusercontent.com/69117052/147763751-b1560c81-d3b5-478d-910b-e56bc3c2fc33.JPG)

**Comment by Vauryx** [comment]
Resolved with new mirror image update
