### ISSUE TITLE
Magic Missile spawning too many darts with v9 and/or v9-MidiQOL

### ISSUE THREAD

**Issue by Seamonster73** [Vauryx/AdvancedSpellEffects#55]
Just for information purposes, on the latest versions of Foundry & MidiQOL the Magic Missile spell spawns darts that hit (Foundry core) targeted icons before the darts have been assigned via the Select Target popup screen.

Once targets have been selected via the Select target screen, and you click 'Done', another round of darts are fired. However, this now seems to spawn too many darts. In my case, approx 12 darts seem to get fired at the target, when it should be three.

The correct number of darts were rolled in the chat window however.

As a secondary issue (and this may only happen for the GM), it seems possible to triple click a target to assign three darts but the second or third click opens the target's character sheet instead of assigning a dart. When this happens, the Select Target screen registers three targets as having been assigned, when in fact only two have registered. No more targets can be assigned until the window is closed and the spell re-cast. If instead you click 'Done' only two hits are rolled.

**Comment by Vauryx** [comment]
Could you see if the issue persists with the new update? Thanks!

**Comment by Seamonster73** [comment]
Hi Vauryx,

It looks like it is still happening for me, but it looks like it's caused by some kind of conflict with MidiQOL. I tried to recreate the issue in a clean new world - It doesn't happen if I just enable the bare minimum of modules required for ASE and AA. 

But as soon as I install MidiQOL, without changing any of it's settings from default, the issue occurs.

However, it's not actually breaking anything - Dice get rolled correctly etc so from a gameplay point of view this probably isn't a high priority issue.


Steps to recreate:

- Create a new world
- Enable the modules for AA and ASE (I added all of the JB2A and Tinker's modules as well etc etc)
- Create a scene and add some actors (I used the ones from the Starter Heroes SRD)
- I then tested Magic Missile to confirm that the issue didn't occur
- I then enabled modules such as DAE that usually get installed with MidQOL. Retested, still no issue.
- Then install MidIQOL. 

I ended up having these modules enabled:

![image](https://user-images.githubusercontent.com/85457807/150633997-093cf84c-48c5-4ea1-90bc-6b964e8fc2c1.png)
(plus WarpGate which is cut off at the end of that image)

- Then retest (without changing any of the MidiQOL settings)
- To test, I did the following:
   - Select a PC with the Magic Missile spell
   - Target another token (via the 'T' keybind shortcut)
   - Open the first character's sheet and cast Magic Missile
   - Without Midi installed, the targeted token is un-targeted and the dialogue box to select targets opens
   - With Midi installed the token is un-targeted, the dialogue box opens, AND three missiles are spawned
   - Then left-click the target three times to assign the darts, and click done.
   - Without Midi installed: Three darts are fired
   - With Midi installed: Multiple darts are fired (possibly 9 in total?)

Here's a gif showing the issue:

![ASE](https://user-images.githubusercontent.com/85457807/150634502-9a4e3beb-639d-460f-a1ed-816e064bea04.gif)



There's also another minor issue; When first converting the Magic Missile spell to an ASE the initial/default settings look like this:

![image](https://user-images.githubusercontent.com/85457807/150633345-25b58313-5e72-4422-85bb-203c4aa0c360.png)

I think this should initially be set to the following instead:

![image](https://user-images.githubusercontent.com/85457807/150633392-78c53041-7014-487c-9d87-e6ae789cde18.png)


Hope this helps! (and apologies in advance if it turns out this is 'user error'...)

**Comment by Haxxer** [comment]
Have you disabled Automated Animations on the spell?

**Comment by Haxxer** [comment]
The first three darts comes from Automated Animations most likely, I recommend disabling it on the item.

**Comment by Seamonster73** [comment]
Yes, it seems like AA is triggering at some point, but it doesn't happen with just AA and ASE enabled. It only happens when AA, ASE and Midi are enabled.

I'll give disabling AA's autorec on this spell a go, but I thought it was worth mentioning as you might continually get people asking about this if they have the same combination of modules enabled.

**Comment by Seamonster73** [comment]
Yep, it looks like deleting it from AA's autorec settings fixes the issue.

**Comment by Vauryx** [comment]
Yeah - AA and ASE are technically usable together so I haven't made it required to disable one. They each do their animations separately so its possible to combine the effects if one wanted to. Generally speaking, unless you have a specific reason for it, only one should be enabled for an item.
