### ISSUE TITLE
steel wind strike errors out due to sequencer database issue

### ISSUE THREAD

**Issue by SR5060** [Vauryx/AdvancedSpellEffects#56]
![image](https://user-images.githubusercontent.com/85184490/148239004-a55a3dca-2d6f-4c75-ad54-84f65103c951.png)
foundry 9.238
dnd 1.5.6
sequencer 1.3.5
ase 0.8.5.5

**Comment by arcanjl** [comment]
I have this same issue, but on all spells that convert to ASE. Once I click convert, it gives me this error.
foundry 9 Build 242
dnd ? 5e?
sequencer 2.0.7
ase 0.8.5.5
JB2A 0.3.4

**Comment by SR5060** [comment]
It's probably just due to v9 incompatibility

**Comment by Vauryx** [comment]
Could you try again withASE v0.9? Thanks!

**Comment by Vauryx** [comment]
Closing due to dormancy

**Comment by SR5060** [comment]
Apologies, I hadn't been able to test this until now, but I checked it out this morning and am still receiving a similar error:

![image](https://user-images.githubusercontent.com/85184490/151811012-d0001ee2-df09-437c-9e6f-dd95a6a7c6e0.png)

sequencer 2.0.13
ASE 0.9.1.1
foundry 9.245
dnd5e 1.5.7

**Comment by Vauryx** [comment]
Are you upto date with JB2A? There was a change to the DB a bit ago where that anim was added it

**Comment by SR5060** [comment]
Yea I was just thinking about that, I think I'm two releases behind. Let me update that and try again

**Comment by SR5060** [comment]
yea I did a full refresh on JB2A and it still throws the error. other effects don't seem to throw it so I'm wondering whether that specific animation file path is just out of date

**Comment by Vauryx** [comment]
can you check if your sequencer DB looks like this
![image](https://user-images.githubusercontent.com/32877348/151917203-5bc01576-2e08-487b-b920-19536fb0d06c.png)

**Comment by Vauryx** [comment]
The sequencer DB can be accessed by the three discs icon in this screenshot

**Comment by SR5060** [comment]
that would do it, the sequencer database is totally blank. odd. Ok I'll post that on that module to figure out what could be causing the issue

**Comment by SR5060** [comment]
jb2a module has to be active, I didn't realize that
