### ISSUE TITLE
Detect Magic Effects not showing up

### ISSUE THREAD

**Issue by EikePeace** [Vauryx/AdvancedSpellEffects#59]
The Circle effects from Detect Magic are somehow not showing up.
The Wave & continous circle are missing.

**Comment by Vauryx** [comment]
Please try again with the 0.9 update of ASE and let me know if the issue is persisting. thanks!

**Comment by EikePeace** [comment]
It works now.
Only thing that is a bit off is the Delay between deleting the concentration (the circle instantly disappears) and the unraveling animation.

**Comment by Vauryx** [comment]
yeah unfortunately that's just a timing issue due to internet latency. Not much that can be done about it
