### ISSUE TITLE
So many problems...Need help..

### ISSUE THREAD

**Issue by Kirin92** [Vauryx/AdvancedSpellEffects#6]
Alright. I wanted to try out Advanced Spell Effects and the Wiki is a bit confusing for someone who can't read the codes....

Now... ugh... I tried out detect magic... somehow (I checked the tag on that almiraj token) the "magical" tag doesn't work. 
Then I tried to disable the animation of detect magic. I don't know how and I thought with times-up would it would disappear. 
Didn't work. So I updated the token and everythig was normal again. Well... I tried detect magic, darkness and call lightning a few times and still don't know how to delete some effects. I reloaded foundry and now.... look at that. All effects are there again.... partially stacked (like the circle for detect magic) 

Pls help.
-detect magic doesn't work with "magical" tag
-can't delete effects
-they don't run out of time
-where I can edit the spell code? 
![90gcBZw](https://user-images.githubusercontent.com/52088060/136035152-f3f286af-7efc-4973-8cdb-0cb7ce7f39ed.png)

**Comment by Vauryx** [comment]
Hey
- For detect magic, there needs to be a magical tag, as well as a spell school tag. So something like this "magical, evocation".
- If there are any lingering effects, they can always be deleted by removing them via the Sequencer Effect manager. 
![image](https://user-images.githubusercontent.com/32877348/136060812-51978a4e-87be-4c63-8390-32741d352f73.png)
Its the middle icon there.
- effects are tied to MIDI-QOL concentration. Is your concentration being handled by MIDI?
- I'm not sure what you mean by that last request? Where you can make changes to the spell itself? You're free to root around the module files and make any changes you want.

**Comment by Kirin92** [comment]
Okay little update.
I managed to delete the darkness and call lightning effect like you said.

- the detect magic works now but if I wanna end the spell and toggle the effect in the sheet... It deletes the concentration icon but the magical ring is still there. (is it because I use tidy5esheet?)

- what I mean of the last request is: in the wiki it says I can change the effect via midi but I don't know where I can change that.

**Comment by Vauryx** [comment]
- The MIDI concertation settings are in the workflow settings yea. The very last section is about Concentrations on that page. 
- Ah, that is possible for a few of the spells only, and only a few changes are possible for those spells. There are optional arguments that can be passed to spells like detect magic to change the color of the effects. Which spells are you asking about specifically?

**Comment by Kirin92** [comment]
Okay thank you. I still try to figure out what I need to check in the workflow settings.

For the edit: I want to change the circle for detect magic. ~

**Comment by Vauryx** [comment]
Btw you can contact me at Vauryx#4507 on discord for faster replies - 
Would you want to change the effect to a different JB2A effect? or is there a custom effect you're looking to set?

**Comment by Kirin92** [comment]
:D thank you. I will contact you on discord instead! 😄
