### ISSUE TITLE
Has this been abandoned?

### ISSUE THREAD

**Issue by gravagehulk** [Vauryx/AdvancedSpellEffects#60]
This module is still incompatible with 9.0, where almost all of the other modules I use have been updated. There has also been no update or response to any of the issues in over a month. This is the one module preventing me from updating my environment, as I need the functionality in my game.

**Comment by Haxxer** [comment]
This module is not abandoned - Varyux has been busy with real life, as we all do this as a hobby.

**Comment by Vauryx** [comment]
V9 update was just released. All of the github issues and suggestions will be addressed next
