### ISSUE TITLE
[Bug] Eldritch Blast Scaling Working off PC Level not Class Level 

### ISSUE THREAD

**Issue by Tyreal74** [Vauryx/AdvancedSpellEffects#61]
When casting Eldritch Blast its getting the number of beams of the PC level not the class level. 

For example, my PC is 11, 10 Warlock, 1 Fighter, using ASE it says i have 3 beams for EB, which i dont, I get 3 beams at level 11 Warlock

**Comment by Vauryx** [comment]
Resolved on the discord
