### ISSUE TITLE
Witch Bolt Issues with Midi-qol

### ISSUE THREAD

**Issue by aprusik** [Vauryx/AdvancedSpellEffects#64]
After attacking with Witch Bolt, the continuous stream appears, but if Midi-qol is installed it doesn't seem to update to move if either the caster or target are moved, nor does it disappear if out of range:
![image](https://user-images.githubusercontent.com/29558544/150654207-8fb81840-bb6c-4352-bcee-479eaf5ceca8.png)

![image](https://user-images.githubusercontent.com/29558544/150654204-d7edb3a1-e5d7-4cc4-990c-eb170adecc13.png)
Without Midi-qol, this functions as intended. Other modules included only those required for ASE.

As a side note, it seems Witch Bolt no longer functions exactly as it says in the Wiki, now giving the player a temporary spell to cast instead of a prompt. What is the intended way to 'end' Witch Bolt? Do you just have to delete all the effects manually? It seems even with Midi-qol disabled, breaking range does not remove the "Activate Witch Bolt" at-will spell.

Foundry Version: 9.242
DnD 5e Version: 1.5.7
ASE Version: 9.0.2

**Comment by Vauryx** [comment]
is MIDI handling your concentration? If MIDI is installed it will need to be the one handling concentration automation for anything related to concentration to work properly

**Comment by aprusik** [comment]
Ah, yes! the concentration was the issue. Thank you for pointing that out!

The only problem I see then is the at-will "Activate Witch-Bolt" spell doesn't disappear, though I'm not sure if that is expected behavior or not.  If it isn't, I can make a separate issue for that if you want, since it's not related to Midi.

**Comment by Vauryx** [comment]
it should disappear when concentration ends.
There is a bug that I'm currently working on addressing where if a spell that adds an 'at-will' spell is cast multiple times without the previous iteration having been removed properly it will cause issues. 
In the mean time, the easiest way to fix it is to hit this 'revert' button on the actor that is experiencing the issue until it goes away 
![image](https://user-images.githubusercontent.com/32877348/150658094-6799ebf8-6d1a-4629-ae29-170018d99742.png)

**Comment by aprusik** [comment]
Awesome! The revert button _does_ work. I didn't even realize that was an option! Now that I know the concentration effect takes care of it that clears up a lot of my confusion. Thank you for the help!

I think that addresses everything, so I would consider this closed.
