### ISSUE TITLE
Call Lightning Error

### ISSUE THREAD

**Issue by Gazkhan** [Vauryx/AdvancedSpellEffects#66]
When the "Active Call Lightning"  spell is rolled, the template appears but an error appears and another error when template placement is confirmed : 
![image](https://user-images.githubusercontent.com/34525758/150687217-411edfd7-103d-4ffc-821f-49d02b34954f.png)

I've tried and had the same result with and without Midi QOL.
Other modules installed are : 
ASE v0.9.0.2
Sequencer v2.0.10
SocketLib v1.0.10
Tagger v1.2.3
WarpGate v1.13.4

This error was reported by @Draigus on Discord and I was able to replicate. Hopefully that helps ! 
Let me know if I can help out in any way 👍

**Comment by Gazkhan** [comment]
Apparently, Honeybadger knows what's going on and will fix it on Warpgate's side !

**Comment by Vauryx** [comment]
fixed via warpgate update
