### ISSUE TITLE
[BUG] Spiritual Weapon not using the right spellcasting modifier 

### ISSUE THREAD

**Issue by Gieff** [Vauryx/AdvancedSpellEffects#67]
Tested with: Core v9.242, DnD5e 1.5.7, and only the modules needed for ASE

Issue: `casterActorRollData.mod` is not the correct spellcasting modifier.
Before ASE 0.8.5 was working as intended (after the update never used the spell in my game, so I don't know if is a problem from that update)

Tested with 
- a PC cleric, with default spellcasting mod, Wisdom 
- custom PC with Charisma spellcasting mod
- a NPC with Wisdom spellcaster mod
- another NPC with Charisma mod

The mod used was from another ability score, like strength or dexterity or even constitution. 
It seems that uses the roll data from the last item rolled, not the current one.

PC cleric case:
![image](https://user-images.githubusercontent.com/84387556/150985604-407ce9c3-6f92-4acd-9557-e5c8a519ae0a.png)

Probabily it needs the roll data from the spell `item` and not from the `actor` for the correct modifier.
I can't understand why, but simply adding a `item.getRollData();` after `item` declaration, also updates `casterActorRoll` with the current spell item.

After adding `item.getRollData();` at line 14 in spiritualWeapon.js
![image](https://user-images.githubusercontent.com/84387556/150985740-66278965-3717-4b4f-ad9f-defabed70e90.png)

**Comment by Vauryx** [comment]
Would you mind exporting any of the actors you tested this with which were experiencing the problem? I am trying to recreate the issue but have been having some trouble.

**Comment by Gieff** [comment]
The actor with the issue: [fvtt-Actor-kinlek.txt](https://github.com/Vauryx/AdvancedSpellEffects/files/7969887/fvtt-Actor-kinlek.txt)

My game world is probaly bloated with all old and new modules (110+), and also localized. I can no longer recreate the issue (midi-qol last update?), the modifier is always the strength and not the last item rolled.

BUT, i found similar issue that can be easily recreated: 
1a. cast spiritual weapon. the modifier is correct
1b. cast spiritual weapon, do NOT consume the spell slot. the modifier is correct
2. use another attack roll, such as a weapon
3. cast spiritual weapon do NOT consume the spell slot. the modifier is now 0

Sample video

https://user-images.githubusercontent.com/84387556/151780911-a95fc2b8-6949-43ff-ba51-1c71068b2e4a.mov

The 2 issues are probabily related, if I add back my "fix" the modifier is always the right one.

**Comment by Vauryx** [comment]
Resolved with 0.9.1.2
