### ISSUE TITLE
Animate Dead doesn't show corpses.

### ISSUE THREAD

**Issue by BlackSwampDM** [Vauryx/AdvancedSpellEffects#68]
I had animated dead up and running no problem.  After a friend said he had problems I went in to see what was up. Now when I cast with to 0hp tokens next to the caster I see 0 corpses to raise. This after your last update. Has anyone else besides me and my Reddit buddy have problems?

**Comment by Vauryx** [comment]
There was a small but that made it through in the last update. I will release it's fix today

**Comment by BlackSwampDM** [comment]
Thanks man, much appreciated.

**Comment by Vauryx** [comment]
Should be fixed with ASE v0.9.1

**Comment by BlackSwampDM** [comment]
Awesome, thanks!
