### ISSUE TITLE
Conflict error at startup

### ISSUE THREAD

**Issue by MorganVergara** [Vauryx/AdvancedSpellEffects#69]
Got this message when I started my game:

![image](https://user-images.githubusercontent.com/30846057/151726539-f37265b7-9c0e-4cf3-97f1-d1b1147d8ecd.png)

The console shows:

![image](https://user-images.githubusercontent.com/30846057/151726564-b4882ea4-46b6-4dae-ad8d-988ff2990e3c.png)

I was able to replicate it with the following environment:

Foundry 9.245
D&D 5E 1.5.7

The following modules were active:

![image](https://user-images.githubusercontent.com/30846057/151726839-57552e30-a2c9-4fc6-a6ac-224d8b878086.png)

This happened just this evening. This afternoon, all was working well, so it's a recent change.

Thanks,

Morgan

**Comment by Vauryx** [comment]
hey - yes I found out about a conflict with DF quality of life module with the new Wall of Force update. You can turn these settings off to get rid of the conflict 
![image](https://user-images.githubusercontent.com/32877348/151731271-213041d4-e11b-458a-a4af-1dacc57e5e2a.png)

**Comment by Vauryx** [comment]
Resolved in 0.9.1 - The new functionality will only be used if DF isn't enabled
