### ISSUE TITLE
Auto apply damage via Midi qol?

### ISSUE THREAD

**Issue by callmeGeorgeRR** [Vauryx/AdvancedSpellEffects#70]
Great module! I was wondering how to enable auto applying damage to spell targets via midi qol. Are there any midi qol settings or other modules you are expecting to do this? 

I have auto damage working on all my other non ASE spells and weapons, etc. but ASE just generates a whispered card that states the save and damage but does not actually apply the damage to the tokens. Specifically I am trying out scorching ray and activate call lightning. Thunder step seems to auto save then auto apply the damage. 

Thanks for any suggestions or answers. Again great module!

**Comment by Vauryx** [comment]
Could you export your MIDI settings and send them my way?  Since MIDI-QOL is such a granular module, it would be helpful if I could test it using your exact MIDI settings.
Thanks!

**Comment by callmeGeorgeRR** [comment]
Sure. I am running v9 foundry on the Forge. I am running midi 0.9.01 as I have had other issues with newer versions. Mostly with clickable item cards and advantage/disadvantage issues.

[auto damage midi qol.zip](https://github.com/Vauryx/AdvancedSpellEffects/files/8025170/auto.damage.midi.qol.zip)

**Comment by callmeGeorgeRR** [comment]
I updated to ASE 0.9.1.2 and Midi 0.9.10 and it seems to be working now. Both Call Lightning and Scorching Ray auto apply damage. Not sure what the issue was but these seemed to have fixed it.
