### ISSUE TITLE
Beam Spell Sound Adjustments

### ISSUE THREAD

**Issue by saneronsds** [Vauryx/AdvancedSpellEffects#71]
Currently behavior for Beam Spell sound effects is to play one sound per-beam-- which can lead to a lot of 'sound stacking.'

Would it be possible to have eldritch blast and other multi-beam spells only play their sound effects once? 
Maybe a toggle-able setting?

Not sure if this behavior is the same for other spells like Magic Missile et al.

**Comment by Vauryx** [comment]
Added in 0.9.1.2
