### ISSUE TITLE
Breaks vision of pre-existing tokens when first going to a map

### ISSUE THREAD

**Issue by Portacustos1** [Vauryx/AdvancedSpellEffects#74]
Several users noticed a problem temperamentally with vision when dragging players to a pre-set-up map where it would give them an error saying "you do not own a token with vision on this scene", and if you delete and re-create a token it would fix it for them, but they wouldn't see other player characters on the map. 

It wasn't easy to pin down, as GM vision was never impaired, and not on occurring when re-loading the map, so Find the Cultprit wouldn't work. After some months, we think we've found it to be ASE. 

My previous post in the Foundry discord is here - https://discord.com/channels/170995199584108546/486930822465716249/914554715990261810

I know other users had the same issue here https://discord.com/channels/170995199584108546/486930822465716249/938650845527048272 and here https://discord.com/channels/170995199584108546/486930822465716249/944069593285132379

A few of us have now tested with players without ASE and haven't had the issue.

**Comment by Vauryx** [comment]
Yeah this is a high priority issue I'm currently looking into. Thanks for the detailed write up! That helps a lot.

**Comment by Vauryx** [comment]
Could you try updating and see if the issue persists? Also, can this be replicated at all in a fresh world with just ASE and its required modules enabled?

**Comment by Vauryx** [comment]
Could you please try it now? I believe this issue should be fixed with the most recent update (0.9.1.4)

**Comment by Vauryx** [comment]
fixed with 0.9.1.4
