### ISSUE TITLE
[Bug] Missing sound with Summon function

### ISSUE THREAD

**Issue by RavenknightDM** [Vauryx/AdvancedSpellEffects#76]
Hi! Thanks for the mod.
Noticed a problem when creating summon spells. For some reason the  Portal Closing Sound effect will not save. Nothing big of course.
Thanks again
![Missing Sound](https://user-images.githubusercontent.com/53635985/155558201-ed627f39-276b-439e-a133-c61e1e138709.png)
.

**Comment by Vauryx** [comment]
Fix is pushed, should be out with the update tonight
