### ISSUE TITLE
[Bug] Missile Dialog creates an invisible Ray to target on a remote server.

### ISSUE THREAD

**Issue by Brimcon** [Vauryx/AdvancedSpellEffects#83]
Foundry Version 9.255
DnD5e Version 1.5.7
Advanced Spell Effects 0.9.1.4
Warp gate 1.13.6
Midi-QOL 0.9.31
All Prerequisites updated to latest versions. (JB2A, Libwrapper, Sockitlib, Tagger.)

Continuing from a Discord Discussion. Casting Eldritch Blast (And possibly Magic Missile and Scorching Ray) creates a second dialog upon hitting a target.
This second Dialogue will not render and the canvas thinks that you are trying to target something with that spell and will react to both left and right clicks.
The Easiest way to identify that the error is occuring is to give the spell a Target Marker Sound.
![image](https://user-images.githubusercontent.com/7198283/157900194-7616ac65-6347-4dc1-be3a-1c9c497343ec.png)
Without the actual dialogue box rendered, right clicking a token prints this error in Console.
```js
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'missilesAssigned')
[Detected 1 package: advancedspelleffects]
    at MissileDialog._removeMissile (missile-dialog.js:206:82)
    at MissileDialog._handleClick (missile-dialog.js:141:22)
    at HTMLBodyElement.dispatch (jquery.min.js:2:43064)
    at HTMLBodyElement.v.handle (jquery.min.js:2:41048)
```
Clicking on a token in this state will place a 'target' icon on the token for a brief time until it vanishes, but the error remains.
Casting Eldritch Blast again in this state will give an additional beam that does nothing
![image](https://user-images.githubusercontent.com/7198283/157901097-a4faa7fe-edba-4473-8136-7173dea97d5c.png)
![image](https://user-images.githubusercontent.com/7198283/157901208-1f7841c5-1c71-4939-a27c-257a92856d40.png)
If you remove a target with a new cast in this state, the Select Targets will show 0 Beams
![image](https://user-images.githubusercontent.com/7198283/157901481-779174ac-ea77-4410-83a5-84d35f6bb097.png)
Hitting Done here will still cast the spell as normal against the initial target.

This occurs on a Remote Server only, not on a self Hosted server..
Unsure if related, but worth posting. This Warning occurs when you hit a target.
```js
foundry.js:15096 
You are passing a Token instance to _getSpeakerFromToken which now expects a TokenDocument instance instead
_getSpeakerFromToken @ foundry.js:15096
getSpeaker @ foundry.js:15044
DamageOnlyWorkflow @ workflow.js:2520
_updateObject @ missile-dialog.js:440
await in _updateObject (async)
_onSubmit @ foundry.js:3855
```
Another thing noticed: It renders the Missile Dialog at the end of Attack and Damage rolls, Possibly Related?
![image](https://user-images.githubusercontent.com/7198283/157968926-4519fc69-de80-4c19-b49a-04c6bc92bfbf.png)

Edit: Removed MidiQOL as being the error.

**Comment by Vauryx** [comment]
Would you be able to confirm if this is still happening for you with the newest MIDI update? Thanks!

**Comment by Brimcon** [comment]
It appears to no longer occur. Whatever fixed it, is fixed.

**Comment by Vauryx** [comment]
Woo, I'll take it!  
I know MIDI has made some changes to the workflows recently so I'm sure it was something in there that caused it. Appreciate your detailed writeup
