### ISSUE TITLE
Missile dialog seems to have a race condition when midi-qol auto damage is enabled.

### ISSUE THREAD

**Issue by Eligarf** [Vauryx/AdvancedSpellEffects#86]
[ase-missile-problem.zip](https://github.com/Vauryx/AdvancedSpellEffects/files/8250185/ase-missile-problem.zip)

I'm running into a problem on Forge v9.255 (DnD5e 1.5.7) with both scorching ray and magic missile once the proper number of targets have been selected and Done has been clicked in the dialog box. The missiles seem to fire off properly when targeting a 1000hp training dummy, but the actual result on the target can be anything between no damage done and it losing nearly all of its 1000hp from a 3-dart magic missile. Even worse, the targeting mode of the dialog is still running, so selecting any tokens yields a message about exceeding the number of targets even though I'm dealing with subsequent characters' turns. The only thing that clears this up to to reload the page. It behaves exactly like how I'd expect a race condition to behave, but of course I'm speculating.

I've included a moduleList.json file with the minimal set of modules I need to recreate the problem as well as listing them below. I also have the midi-qol settings I used to march the problem down to the 'auto apply damage to target' setting. The included file has this field set to none, you will need to set this one field to 'Yes + damage card' to recreate the issue. I also included two log files, one with all debug info turned on for midi.

Active Modules:
----------
Advanced Spell Effects v0.9.1.4;
Forien's Copy Environment v2.0.7;
JB2A - Patreon Complete Collection v0.3.8;
libWrapper v1.12.4.0;
Midi QOL v0.9.33;
Sequencer v2.0.16;
socketlib v1.0.10;
Tagger v1.3.4;
Tidy UI - Game Settings v0.1.31;
Warp Gate v1.13.6;

**Comment by Brimcon** [comment]
I wonder if this is related to #83.

**Comment by Vauryx** [comment]
Would you be able to confirm if this is still happening with the newest update to MIDI?

**Comment by Eligarf** [comment]
I still get related issues with 9.266 foundry, 9.42 midi, and 9.1.4 ASE. I target three orcs with scorching ray, things seem fine. I cast it again, the first time I click on one of the orcs it get two rays assigned. I right click, zero rays assigned. Left click again, two rays assigned, right click, back to zero. Pick a different orc, same thing, two rays or zero rays.
![image](https://user-images.githubusercontent.com/16523503/162586880-efd39493-8958-4f12-b49c-ab15feee60bd.png)

**Comment by Vauryx** [comment]
Strange, could you try this now with the ASE 0.9.2.1 update? It should have fixed a lot of these issues.

**Comment by Eligarf** [comment]
9.2.1 seems to fix it. Fingers crossed!

**Comment by Vauryx** [comment]
fixed with 0.9.2.1
