### ISSUE TITLE
Steel Wind Strike uses wrong to hit modifier.

### ISSUE THREAD

**Issue by Orbdamu** [Vauryx/AdvancedSpellEffects#89]
When using Steel Wind Strike, the used hit modifier is bugged. the casters Spell Attack Mod is +8, yet he still regularily rolls 5 or 6 as total hit values.

Edit: after further investigation, this behavior randomly occurs with scorching ray as well, maybe happens to all multihit spells with attack rolls. It seems that on random occasions, it only takes the proficiency modifier and not the spellcasting modifier aswell (seen when hovering over the hit values of scorching ray). Since for steel wind strike, no dice rolls can be viewed, I cannot confirm that the reason for the bug is the same, but I wanted to include these findings in the bug report.

**Comment by Vauryx** [comment]
confirmed to hit modifiers are behaving strangely. Working on the fix thanks for submitting the ticket!

**Comment by Vauryx** [comment]
This should be fixed now for the multi hit spells as well as steel wind strike. Could you test now with the 0.9.2.1 update? Thanks!

**Comment by Vauryx** [comment]
fixed with 0.9.3

**Comment by Orbdamu** [comment]
Steelwind strike seems to still be broken in terms of to hit modifiers
![steelwindstrike](https://user-images.githubusercontent.com/16311455/167176433-467163d0-3896-4cd2-8429-a56f74025303.png).
Scorching Ray seems to work now. I did redo the steelwind strike (opened a new blank slate and used ASE again) to make sure it is not a bug of the old spell version. Sorry for being so late, just handed in my Master Thesis and was therefore pretty busy the last month
