### ISSUE TITLE
spritual weapon error: missing type, weapon attack does not incorporate caster attributes

### ISSUE THREAD

**Issue by SR5060** [Vauryx/AdvancedSpellEffects#9]
![image](https://user-images.githubusercontent.com/85184490/137502470-95bd802e-0abd-4efe-bd3b-939af53c10fa.png)

the system throws the above error when trying to summon a weapon and (probably related to the above issue) uses the weapon attributes to determine attack and damage attributes vs the spellcaster. screenshots of the actor set up are as follows in case there is something incorrect with my setup:

![image](https://user-images.githubusercontent.com/85184490/137503176-ce88e7e8-faf2-4885-a776-b3724fbf2e12.png)

![image](https://user-images.githubusercontent.com/85184490/137503238-b2c6e4b7-01c8-4e1b-9421-85428f746f18.png)
![image](https://user-images.githubusercontent.com/85184490/137503291-719fa25e-3857-45f3-9232-61ed21bf6488.png)

**Comment by Vauryx** [comment]
No problem! Glad you got it working!
