### ISSUE TITLE
Eldritch Blast Not Scaling on NPCs

### ISSUE THREAD

**Issue by webmaster94** [Vauryx/AdvancedSpellEffects#90]
Eldritch Blast does not scale properly with either CR or spellcasting level (what it should scale with). I don't know if other cantrips are affected.

**Comment by Vauryx** [comment]
Could you try it with ASE 0.9.2.1? Thanks!

**Comment by webmaster94** [comment]
Just did some testing with find the culprit, just to be sure there was no module incompatibility. You should definitely have WarpGate be a hard dependency if even spells such as Eldritch Blast require it to work by the way. I can confirm the update did not fix the problem. It still just provides one beam when there should be three.

**Comment by Vauryx** [comment]
You're right, I'll add that in as a dependency. 
Would you be able to export the actor you're trying this on and posting the file here?

**Comment by webmaster94** [comment]
Sure will do.

**Comment by Vauryx** [comment]
nevermind, I've got the fix pushed already. Update should be out tonight

**Comment by Vauryx** [comment]
fixed with 0.9.3
