### ISSUE TITLE
[Suggestion] Steel Wind Strike option to customise damage roll

### ISSUE THREAD

**Issue by Tacto-Tonkertink** [Vauryx/AdvancedSpellEffects#91]
Would it be possible to have a menu option to change the damage roll on Steel Wind Strike? Possibly attack roll formula and number of targets as well? 

Very lovely work by the way!

**Comment by Vauryx** [comment]
The number of targets is upto the caster. The spell will carry out a strike for each target selected before the spell is cast. 

The damage formula should be changeable in the settings with the update tonight

**Comment by Vauryx** [comment]
added in 0.9.3
