### ISSUE TITLE
Scorching Ray Shift-Click Advantage

### ISSUE THREAD

**Issue by VoltCruelerz** [Vauryx/AdvancedSpellEffects#92]
Could we get this as an option? Shift+Click is often the keybinding for advantage, not Alt+Click. It would be more clear for my players if it were consistent.

**Comment by Vauryx** [comment]
Hey, Yeah ASE currently doesn't have a way to deal with different crit rules. I will be working on that for Eldritch Blast and Scorching Ray in the near future. 
It should work fine without MIDI-QOL. It will ofcourse not apply any damage or check for hits though. The effect should play out just fine though. Did you have issues without MIDI?

**Comment by VoltCruelerz** [comment]
> I will be working on that

Cool!

> issues without MIDI

Yeah. Without it, it doesn't actually do any targeting or rolls.
