### ISSUE TITLE
BUG about magic missles and chain lightning

### ISSUE THREAD

**Issue by deedlitelf** [Vauryx/advancedspelleffects#93]
I found them in the 0.9.5.
For magic missles, the setting panel links to Animate Dead because the return data is undefined or NaN. So the magic missles could not work as wish.
For the chain lightning, the secondary bolts will make a damage(heal) with the number NaN, so it will kill all the targets no matter how many HP they have.

**Comment by deedlitelf** [comment]
FVTT is 9.268
midi-qol, warpgate and other modules are the newest version

**Comment by Vauryx** [comment]
very strange, do you have any other modules enabled? Haven't seen that one before at all

**Comment by deedlitelf** [comment]
> very strange, do you have any other modules enabled? Haven't seen that one before at all

Good idea, I'll have a try.

**Comment by deedlitelf** [comment]
> very strange, do you have any other modules enabled? Haven't seen that one before at all What do you mean the setting panel links to animate dead? You can generally change the drop down to apply the magic missile instead

Hi, Vauryx. I've done. In new test environment, the magic missles make a good job. But the chain lightning still kill all the secondary targets.
And that's the mod list in the test:
    _Advanced Spell Effects v;
    Dynamic Active Effects SRD v;
    Dynamic effects using Active Effects v;
    JB2A - Patreon Complete Collection v;
    libWrapper v0;
    Midi QOL v;
    Sequencer v;
    socketlib v;
    Tagger v;
    Tidy5e Sheet v;
    Tidy UI - Game Settings v;
    Warp Gate v;_
