### ISSUE TITLE
Targeting issue

### ISSUE THREAD

**Issue by TaPipito** [Vauryx/advancedspelleffects#94]
Hi, I have a problem with the targeting of spells like call lightning or moonbeam. 

When I try to place the target template I can only select the intersection of the grid squares and not the square center. 

Can someone help me understanding the problem? I'm using the lady stable version of foundry and all the modules are up to date.

**Comment by Vauryx** [comment]
Hey, that is actually intended behavior.  The spells state that a point you can see must be chosen to place the cloud or beam, and the grid rules state that a point you can see are the intersections of the grid squares. I will be adding in an option in the near future for those spells to have a definable setting though
