### ISSUE TITLE
Not able to 'detect stuff'

### ISSUE THREAD

**Issue by GeoffPell** [Vauryx/AdvancedSpellEffects#95]
Hello - I can't work out what I'm doing wrong:

Detect magic works fine:
![detect_magic](https://user-images.githubusercontent.com/1830305/166902186-81fbbf81-dfc6-4852-931e-04ef69f4346d.png)

But I can't do anything to make poison or good/evil work 
I've tried custom tags, db path/file path but I can't make it work?
![posion](https://user-images.githubusercontent.com/1830305/166902400-f774446e-dfb0-4438-b287-af36fa14310e.png)

thanks for any help and great mod!

**Comment by Vauryx** [comment]
For something to be detected and display an effect, a "ase-detect" tag must be set along side any other relevant tags. 

Please refer to the WIKI for more setup instructions

https://github.com/Vauryx/AdvancedSpellEffects/wiki/Currently-Available-Spells#detect-stuff

**Comment by GeoffPell** [comment]
thank you!
