### ISSUE TITLE
Steelwind Strike still bugged (referencing issue #89)

### ISSUE THREAD

**Issue by Orbdamu** [Vauryx/AdvancedSpellEffects#96]
Steelwind strike seems to still be broken in terms of to hit modifiers
![steelwindstrike](https://user-images.githubusercontent.com/16311455/167178414-b7a2312e-9f34-4044-a7bd-25a5d3d6c8f2.png)

Scorching Ray seems to work now. I did redo the steelwind strike (opened a new blank slate and used ASE again) to make sure it is not a bug of the old spell version. Sorry for being so late, just handed in my Master Thesis and was therefore pretty busy the last month.

**Comment by Vauryx** [comment]
Would you mind exporting your actor and sending it here? I'd like to test with your setup if possible

**Comment by Orbdamu** [comment]
Sure. To simplify it, I tested it with a new actor and a newly created spell that I applied the ASE effect on, the behavior is the same
[fvtt-Actor-testactor.zip](https://github.com/Vauryx/AdvancedSpellEffects/files/8646114/fvtt-Actor-testactor.zip)

**Comment by Vauryx** [comment]
Fixed with 0.9.5.6
